ALTER TABLE tasks ADD COLUMN type VARCHAR(256) NOT NULL DEFAULT 'currency_conversion';
ALTER TABLE tasks ALTER COLUMN type DROP DEFAULT;

ALTER TABLE tasks ADD COLUMN payload JSONB NOT NULL DEFAULT '{}';
ALTER TABLE tasks ALTER COLUMN payload DROP DEFAULT;