
services:
  server:
    build: 
      # контекст сборки для доступа к .mod 
      context: ..
      dockerfile: /docker/Dockerfile
    image: simple-server

    # порт для доступа к серверу
    ports:
      - "8085:8085"
    # переменные окружения
    env_file:
      - ../.env
    # environment:


  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_PASSWORD: "pgpass54"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      # инициализация бд
      - ../internal/storage/postgres/sql/:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data: